# Generated by Django 3.2.5 on 2021-07-07 04:46

from django.db import migrations, models
import django_tenants.postgresql_backend.base
import rest_framework.viewsets


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
            ],
            options={
                'abstract': False,
            },
            bases=(rest_framework.viewsets.ModelViewSet, models.Model),
        ),
    ]
