# Generated by Django 3.2.5 on 2021-07-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientView',
        ),
    ]
